# Generated by Django 3.2 on 2021-04-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='web_media/dragons/', verbose_name='Изображение яйцо')),
                ('image_2', models.ImageField(upload_to='web_media/dragons/', verbose_name='Изображение взрослый')),
                ('image_3', models.ImageField(upload_to='web_media/dragons/', verbose_name='Изображение детёныша')),
                ('usual_pic', models.ImageField(upload_to='web_media/info/', verbose_name='Обычный редкость')),
            ],
            options={
                'verbose_name': 'Дракон',
                'verbose_name_plural': 'Драконы',
            },
        ),
        migrations.CreateModel(
            name='PIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='web_media/info/', verbose_name='Изображение яйцо')),
                ('image_2', models.ImageField(upload_to='web_media/info/', verbose_name='Изображение взрослый')),
            ],
            options={
                'verbose_name': 'Дракон',
                'verbose_name_plural': 'Драконы',
            },
        ),
        migrations.CreateModel(
            name='PICweb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='web_media/other', verbose_name='Изображение')),
                ('text', models.TextField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Техническое изображение',
                'verbose_name_plural': 'Технические изображения',
            },
        ),
    ]
