# Generated by Django 3.2 on 2021-04-08 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Draco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountOfFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.IntegerField(default=0, verbose_name='Максимальное кол-во')),
                ('big', models.IntegerField(default=0, verbose_name='Минимальное кол-во')),
            ],
            options={
                'verbose_name': 'Другой способ получения еды',
                'verbose_name_plural': 'Другие способы получения еды',
            },
        ),
        migrations.CreateModel(
            name='AmountOfFoodTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methods', models.TextField(max_length=100, verbose_name='Методы получения')),
                ('about', models.TextField(max_length=2000, verbose_name='Примечания')),
                ('language', models.CharField(max_length=2, verbose_name='Язык')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Draco.amountoffood')),
            ],
            options={
                'verbose_name': 'Другой способ получения еды перевод',
                'verbose_name_plural': 'Другие способы получения еды перевод',
            },
        ),
        migrations.CreateModel(
            name='CalculatorDragons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Дракон для калькулятора',
                'verbose_name_plural': 'Драконы для калькулятора',
            },
        ),
        migrations.CreateModel(
            name='Catalogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_catalog', models.TextField(max_length=200, verbose_name='Тип каталога')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DopInfoElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_info_el1', models.ImageField(upload_to='web_media/info', verbose_name='Картинка1')),
                ('image_info_el2', models.ImageField(upload_to='web_media/info', verbose_name='Картинка2')),
                ('image_info_el3', models.ImageField(upload_to='web_media/info', verbose_name='Картинка3')),
            ],
            options={
                'verbose_name': 'Дополнительная информация по элементу',
                'verbose_name_plural': 'Дополнительная информация по элементам',
            },
        ),
        migrations.CreateModel(
            name='DopInfoElementsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.TextField(max_length=100, verbose_name='Заголовок')),
                ('title_2', models.TextField(max_length=10000, verbose_name='Инфа 1')),
                ('title_3', models.TextField(max_length=10000, verbose_name='Инфа 2')),
                ('title_4', models.TextField(max_length=10000, verbose_name='Инфа 3')),
                ('language', models.CharField(max_length=2, verbose_name='Язык')),
                ('dop_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Draco.dopinfoelements')),
            ],
            options={
                'verbose_name': 'Дополнительная информация по элементу перевод',
                'verbose_name_plural': 'Дополнительная информация по элементам перевод',
            },
        ),
        migrations.CreateModel(
            name='DragonTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('rarity', models.CharField(max_length=20, verbose_name='Редкость')),
                ('description1', models.TextField(max_length=1000, verbose_name='Описание')),
                ('description2', models.TextField(max_length=1000, verbose_name='Получение')),
                ('description3', models.TextField(max_length=1000, verbose_name='Разведение')),
                ('language', models.CharField(max_length=2, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Дракон перевод',
                'verbose_name_plural': 'Драконы перевод',
            },
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ImageField(upload_to='web_media/elements/', verbose_name='Элемент')),
                ('lvl_needed', models.IntegerField(default=0, verbose_name='Требуемый уровень')),
                ('hp', models.IntegerField(default=0, verbose_name='Скейлы здоровья')),
                ('dmg', models.IntegerField(default=0, verbose_name='Скейлы атаки')),
                ('gold_per_hour', models.IntegerField(default=0, verbose_name='Бонус золото/час')),
            ],
            options={
                'verbose_name': 'Свойство элементов',
                'verbose_name_plural': 'Свойства элементов',
            },
        ),
        migrations.CreateModel(
            name='ElementsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_element', models.TextField(max_length=20, verbose_name='Название')),
                ('language', models.CharField(max_length=2, verbose_name='Язык')),
                ('elements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Draco.elements')),
            ],
            options={
                'verbose_name': 'Свойство элементов перевод',
                'verbose_name_plural': 'Свойства элементов перевод',
            },
        ),
        migrations.CreateModel(
            name='InfoFoodTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.TextField(max_length=100, verbose_name='Заголовок')),
                ('title_2', models.TextField(max_length=1000, verbose_name='Инфа 1')),
                ('title_3', models.TextField(max_length=1000, verbose_name='Инфа 2')),
                ('language', models.CharField(max_length=2, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Информация о ресурсе еда перевод',
                'verbose_name_plural': 'Информация о ресурсе еда перевод',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Заказ + данные пользователя',
                'verbose_name_plural': 'Заказы + данные пользователя',
            },
        ),
        migrations.CreateModel(
            name='PicturesStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.CharField(max_length=20, verbose_name='Название картинки')),
                ('attack_pic', models.ImageField(upload_to='web_media/elements/', verbose_name='Атака')),
                ('hp_pic', models.ImageField(upload_to='web_media/elements/', verbose_name='Здоровье')),
                ('gold_pic', models.ImageField(upload_to='web_media/elements/', verbose_name='Золото')),
                ('xp_pic', models.ImageField(upload_to='web_media/elements/', verbose_name='Опыт')),
                ('sale_pic', models.ImageField(upload_to='web_media/elements/', verbose_name='Продажа')),
                ('points_pic', models.ImageField(upload_to='web_media/elements/', verbose_name='Очки за выведение')),
            ],
            options={
                'verbose_name': 'Картинки характеристики',
                'verbose_name_plural': 'Картинки характеристик',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_product_main', models.ImageField(upload_to='web_media/info', verbose_name='Изображение продукта основное')),
                ('image_product_1', models.ImageField(upload_to='web_media/info', verbose_name='Изображение продукта_1')),
                ('image_product_2', models.ImageField(upload_to='web_media/info', verbose_name='Изображение продукта_2')),
                ('catalogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Draco.catalogs')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя продукта')),
                ('price', models.FloatField(default=0, verbose_name='Цена за продукт')),
                ('old_price', models.FloatField(default=0, verbose_name='Старая цена за продукт')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг набора')),
                ('value', models.IntegerField(default=0, verbose_name='Кол-во продукта')),
                ('content', models.TextField(max_length=1000, verbose_name='Контент')),
                ('language', models.CharField(max_length=2, verbose_name='Язык')),
                ('products_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Draco.products')),
            ],
            options={
                'verbose_name': 'Заказ перевод',
                'verbose_name_plural': 'Заказы перевод',
            },
        ),
        migrations.CreateModel(
            name='SchoolsSymbolsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schools', models.TextField(max_length=100, verbose_name='Школы символов')),
                ('info_school', models.TextField(max_length=5000, verbose_name='Информация о школе')),
                ('symbol_1', models.TextField(max_length=50, verbose_name='Тип символа')),
                ('info_symbol_1', models.TextField(max_length=1000, verbose_name='Информация о символе')),
                ('symbol_2', models.TextField(max_length=50, verbose_name='Тип символа')),
                ('info_symbol_2', models.TextField(max_length=1000, verbose_name='Информация о символе')),
                ('symbol_3', models.TextField(max_length=50, verbose_name='Тип символа')),
                ('info_symbol_3', models.TextField(max_length=1000, verbose_name='Информация о символе')),
                ('symbol_4', models.TextField(max_length=50, verbose_name='Тип символа')),
                ('info_symbol_4', models.TextField(max_length=1000, verbose_name='Информация о символе')),
                ('symbol_5', models.TextField(max_length=50, verbose_name='Тип символа')),
                ('info_symbol_5', models.TextField(max_length=1000, verbose_name='Информация о символе')),
                ('language', models.CharField(max_length=2, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Информация о школе символе',
                'verbose_name_plural': 'Информация о школах символов',
            },
        ),
        migrations.CreateModel(
            name='StatsLvl1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element1', models.ImageField(upload_to='web_media/elements/', verbose_name='Стихия 1')),
                ('element2', models.ImageField(upload_to='web_media/elements/', verbose_name='Стихия 2')),
                ('element3', models.ImageField(upload_to='web_media/elements/', verbose_name='Стихия 3')),
                ('dmg', models.IntegerField(default=0, verbose_name='Урон')),
                ('hp', models.IntegerField(default=0, verbose_name='Здоровье')),
                ('gold', models.IntegerField(default=0, verbose_name='Золото/час')),
                ('exp', models.IntegerField(default=0, verbose_name='Опыт за получение')),
                ('sale', models.IntegerField(default=0, verbose_name='Продажа')),
                ('points', models.IntegerField(default=0, verbose_name='Очки за сбор')),
            ],
            options={
                'verbose_name': 'Характеристика на 1 уровне',
                'verbose_name_plural': 'Характеристика на 1 уровне',
            },
        ),
        migrations.CreateModel(
            name='StatsLvl1Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el1', models.TextField(max_length=20, verbose_name='Элемент 1')),
                ('el2', models.TextField(max_length=20, verbose_name='Элемент 2')),
                ('el3', models.TextField(max_length=20, verbose_name='Элемент 3')),
                ('language', models.CharField(max_length=2, verbose_name='Язык')),
                ('stats_lvl1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Draco.statslvl1')),
            ],
            options={
                'verbose_name': 'Характеристика на 1 уровне перевод',
                'verbose_name_plural': 'Характеристика на 1 уровне перевод',
            },
        ),
        migrations.CreateModel(
            name='TheStrengthWeakness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strong1', models.ImageField(upload_to='web_media/elements/', verbose_name='Силен против1')),
                ('strong2', models.ImageField(upload_to='web_media/elements/', verbose_name='Силен против2')),
                ('strong3', models.ImageField(upload_to='web_media/elements/', verbose_name='Силен против3')),
                ('weak1', models.ImageField(upload_to='web_media/elements/', verbose_name='Слаб против1')),
                ('weak2', models.ImageField(upload_to='web_media/elements/', verbose_name='Слаб против2')),
                ('weak3', models.ImageField(upload_to='web_media/elements/', verbose_name='Слаб против3')),
                ('steady1', models.ImageField(upload_to='web_media/elements/', verbose_name='Устойчив к1')),
                ('steady2', models.ImageField(upload_to='web_media/elements/', verbose_name='Устойчив к2')),
                ('steady3', models.ImageField(upload_to='web_media/elements/', verbose_name='Устойчив к3')),
                ('defenseless1', models.ImageField(upload_to='web_media/elements/', verbose_name='Уязвим к1')),
                ('defenseless2', models.ImageField(upload_to='web_media/elements/', verbose_name='Уязвим к2')),
                ('defenseless3', models.ImageField(upload_to='web_media/elements/', verbose_name='Уязвим к3')),
                ('elements_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Draco.elements')),
            ],
            options={
                'verbose_name': 'Сила и слабость элементов',
                'verbose_name_plural': 'Силы и слабости элементов',
            },
        ),
        migrations.CreateModel(
            name='TheStrengthWeaknessTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_about', models.CharField(max_length=20, verbose_name='Элемент')),
                ('language', models.CharField(max_length=2, verbose_name='Язык')),
                ('strength_weakness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Draco.thestrengthweakness')),
            ],
            options={
                'verbose_name': 'Сила и слабость элементов перевод',
                'verbose_name_plural': 'Силы и слабости элементов перевод',
            },
        ),
        migrations.CreateModel(
            name='TypeFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_food', models.ImageField(upload_to='web_media/food', verbose_name='Еда картинка')),
                ('image_type_food', models.ImageField(upload_to='web_media/food', verbose_name='Еда тип картинка')),
                ('lvl_farm', models.IntegerField(default=0, verbose_name='Уровень ферм')),
                ('time_grows', models.FloatField(default=0, verbose_name='Время производства часов')),
                ('food', models.IntegerField(default=0, verbose_name='Кол-во еды')),
                ('xp', models.IntegerField(default=0, verbose_name='Опыт')),
                ('gold_coast', models.IntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Вид продукций еды',
                'verbose_name_plural': 'Виды продукций еды',
            },
        ),
        migrations.CreateModel(
            name='TypeFoodTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_food', models.CharField(max_length=20, verbose_name='Название')),
                ('language', models.CharField(max_length=2, verbose_name='Язык')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Draco.typefood')),
            ],
            options={
                'verbose_name': 'Вид продукций еды перевод',
                'verbose_name_plural': 'Виды продукций еды перевод',
            },
        ),
        migrations.CreateModel(
            name='UsInfoTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.TextField(max_length=100, verbose_name='Заголовок')),
                ('title_2', models.TextField(max_length=10000, verbose_name='Инфа 1')),
                ('title_3', models.TextField(max_length=10000, verbose_name='Инфа 2')),
                ('language', models.CharField(max_length=2, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Дополнительная информация перевод',
                'verbose_name_plural': 'Дополнительная информация перевод',
            },
        ),
        migrations.DeleteModel(
            name='PIC',
        ),
        migrations.RemoveField(
            model_name='dragon',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='dragon',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='dragon',
            name='image_3',
        ),
        migrations.AddField(
            model_name='dragon',
            name='image1',
            field=models.ImageField(default=1, upload_to='web_media/dragons', verbose_name='Изображение яйцо'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dragon',
            name='image2',
            field=models.ImageField(default=1, upload_to='web_media/dragons', verbose_name='Изображение взрослый'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dragon',
            name='image3',
            field=models.ImageField(default=1, upload_to='web_media/dragons', verbose_name='Изображение детёныша'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dragontranslation',
            name='dragon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Draco.dragon'),
        ),
        migrations.AddField(
            model_name='calculatordragons',
            name='dragon1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dragon1', to='Draco.dragontranslation'),
        ),
        migrations.AddField(
            model_name='calculatordragons',
            name='dragon2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dragon2', to='Draco.dragontranslation'),
        ),
        migrations.AddField(
            model_name='calculatordragons',
            name='result',
            field=models.ManyToManyField(to='Draco.DragonTranslation'),
        ),
    ]
