# Generated by Django 3.2 on 2021-04-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Draco', '0004_calculatordragons_dragon_dragontranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragon',
            name='dragon_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Draco.statslvl1'),
            preserve_default=False,
        ),
    ]
