# Generated by Django 3.2 on 2021-04-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Draco', '0005_dragon_dragon_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragon',
            name='element1',
            field=models.ImageField(default=1, upload_to='web_media/elements/', verbose_name='Стихия 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dragon',
            name='element2',
            field=models.ImageField(default=1, upload_to='web_media/elements/', verbose_name='Стихия 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dragon',
            name='element3',
            field=models.ImageField(default=1, upload_to='web_media/elements/', verbose_name='Стихия 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dragon',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
    ]
