# Generated by Django 3.2 on 2021-04-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Draco', '0006_auto_20210408_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dragon',
            name='dragon_info',
        ),
        migrations.AddField(
            model_name='statslvl1',
            name='dragon_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Draco.dragon'),
            preserve_default=False,
        ),
    ]
