# Generated by Django 3.2 on 2021-04-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Draco', '0008_auto_20210408_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description1', models.TextField(max_length=5000, verbose_name='Описание')),
                ('description2', models.TextField(max_length=5000, verbose_name='Получение')),
                ('description3', models.TextField(max_length=5000, verbose_name='Разведение')),
                ('description4', models.TextField(max_length=5000, verbose_name='Получение')),
                ('description5', models.TextField(max_length=5000, verbose_name='Разведение')),
                ('language', models.CharField(max_length=2, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Дракон перевод',
                'verbose_name_plural': 'Драконы перевод',
            },
        ),
    ]
