# Generated by Django 3.2 on 2021-04-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Draco', '0009_mainpagetranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextStatsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000, verbose_name='Информация')),
                ('language', models.CharField(max_length=2, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Текстовая информация сайта',
                'verbose_name_plural': 'Текстовая информация сайта',
            },
        ),
        migrations.AlterModelOptions(
            name='mainpagetranslation',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главная страница'},
        ),
        migrations.AlterModelOptions(
            name='picturesstats',
            options={'verbose_name': 'Картинки для таблицы', 'verbose_name_plural': 'Картинки для таблиц'},
        ),
        migrations.AddField(
            model_name='dragon',
            name='background',
            field=models.ImageField(default=1, upload_to='web_media/other/', verbose_name='Задний фон карточек'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainpagetranslation',
            name='description1',
            field=models.TextField(max_length=5000, verbose_name='Описание_1'),
        ),
        migrations.AlterField(
            model_name='mainpagetranslation',
            name='description2',
            field=models.TextField(max_length=5000, verbose_name='Описание_2'),
        ),
        migrations.AlterField(
            model_name='mainpagetranslation',
            name='description3',
            field=models.TextField(max_length=5000, verbose_name='Описание_3'),
        ),
        migrations.AlterField(
            model_name='mainpagetranslation',
            name='description4',
            field=models.TextField(max_length=5000, verbose_name='Описание_4'),
        ),
        migrations.AlterField(
            model_name='mainpagetranslation',
            name='description5',
            field=models.TextField(max_length=5000, verbose_name='Описание_5'),
        ),
    ]
