# Generated by Django 3.2 on 2021-04-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Draco', '0010_auto_20210416_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementsHomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_1', models.ImageField(upload_to='web_media/elements/', verbose_name='Стихия огонь')),
                ('element_2', models.ImageField(upload_to='web_media/elements/', verbose_name='Стихия ветер')),
                ('element_3', models.ImageField(upload_to='web_media/elements/', verbose_name='Стихия земля')),
                ('element_4', models.ImageField(upload_to='web_media/elements/', verbose_name='Стихия вода')),
                ('element_5', models.ImageField(upload_to='web_media/elements/', verbose_name='Стихия отрава')),
                ('element_6', models.ImageField(upload_to='web_media/elements/', verbose_name='Стихия металл')),
                ('element_7', models.ImageField(upload_to='web_media/elements/', verbose_name='Стихия энергия')),
                ('element_8', models.ImageField(upload_to='web_media/elements/', verbose_name='Стихия пустота')),
                ('element_9', models.ImageField(upload_to='web_media/elements/', verbose_name='Стихия свет')),
                ('element_10', models.ImageField(upload_to='web_media/elements/', verbose_name='Стихия тень')),
                ('element_11', models.ImageField(upload_to='web_media/elements/', verbose_name='Стихия легенда')),
                ('element_12', models.ImageField(upload_to='web_media/elements/', verbose_name='Стихия божество')),
                ('element_13', models.ImageField(upload_to='web_media/elements/', verbose_name='Стихия древняя')),
            ],
            options={
                'verbose_name': 'Стихия для страницы жилища',
                'verbose_name_plural': 'Стихии для страницы жилища',
            },
        ),
    ]
